import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import ClientSideWrapper from "@/components/ClientSideWrapper"; // NavBar component
import { AuthProvider } from "@/context/AuthContext"; // AuthProvider for authentication
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TEC-APT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        <AuthProvider>
          <ClientSideWrapper>
            <Toaster position="bottom-center" />

            {/* Render children inside the main layout */}
            <div className="flex-1">{children}</div>
          </ClientSideWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
