import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import ClientSideWrapper from "@/components/ClientSideWrapper"; // Wrapper for client-side components
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TEC-APT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {/* Client-side wrapper handling stateful components */}
        <ClientSideWrapper>
          <div className="flex-1 ml-2 p-2">
            {/* Render children passed to the layout */}
            {children}
          </div>
        </ClientSideWrapper>
      </body>
    </html>
  );
}
