export const patients = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    gender: "Male",
    phoneNumber: "555-1234",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    gender: "Female",
    phoneNumber: "555-5678",
  },
  {
    id: 3,
    firstName: "Sam",
    lastName: "Wilson",
    email: "sam.wilson@example.com",
    gender: "Male",
    phoneNumber: "555-8765",
  },
  {
    id: 4,
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    gender: "Female",
    phoneNumber: "555-9876",
  },
  {
    id: 5,
    firstName: "Bob",
    lastName: "Brown",
    email: "bob.brown@example.com",
    gender: "Male",
    phoneNumber: "555-4567",
  },
  {
    id: 6,
    firstName: "Charlie",
    lastName: "Green",
    email: "charlie.green@example.com",
    gender: "Male",
    phoneNumber: "555-2345",
  },
  {
    id: 7,
    firstName: "Diana",
    lastName: "Miller",
    email: "diana.miller@example.com",
    gender: "Female",
    phoneNumber: "555-6543",
  },
  {
    id: 8,
    firstName: "Eve",
    lastName: "Davis",
    email: "eve.davis@example.com",
    gender: "Female",
    phoneNumber: "555-1235",
  },
  {
    id: 9,
    firstName: "Frank",
    lastName: "Martinez",
    email: "frank.martinez@example.com",
    gender: "Male",
    phoneNumber: "555-7890",
  },
  {
    id: 10,
    firstName: "Grace",
    lastName: "Taylor",
    email: "grace.taylor@example.com",
    gender: "Female",
    phoneNumber: "555-2346",
  },
  {
    id: 11,
    firstName: "Hank",
    lastName: "White",
    email: "hank.white@example.com",
    gender: "Male",
    phoneNumber: "555-9877",
  },
  {
    id: 12,
    firstName: "Isaac",
    lastName: "Brown",
    email: "isaac.brown@example.com",
    gender: "Male",
    phoneNumber: "555-8766",
  },
  {
    id: 13,
    firstName: "Jack",
    lastName: "Wilson",
    email: "jack.wilson@example.com",
    gender: "Male",
    phoneNumber: "555-7654",
  },
  {
    id: 14,
    firstName: "Kim",
    lastName: "Thompson",
    email: "kim.thompson@example.com",
    gender: "Female",
    phoneNumber: "555-7653",
  },
  {
    id: 15,
    firstName: "Leo",
    lastName: "Garcia",
    email: "leo.garcia@example.com",
    gender: "Male",
    phoneNumber: "555-6542",
  },
  {
    id: 16,
    firstName: "Mia",
    lastName: "Martinez",
    email: "mia.martinez@example.com",
    gender: "Female",
    phoneNumber: "555-5431",
  },
  {
    id: 17,
    firstName: "Nina",
    lastName: "Lopez",
    email: "nina.lopez@example.com",
    gender: "Female",
    phoneNumber: "555-4321",
  },
  {
    id: 18,
    firstName: "Oscar",
    lastName: "Gonzalez",
    email: "oscar.gonzalez@example.com",
    gender: "Male",
    phoneNumber: "555-3210",
  },
  {
    id: 19,
    firstName: "Pam",
    lastName: "Perez",
    email: "pam.perez@example.com",
    gender: "Female",
    phoneNumber: "555-2109",
  },
  {
    id: 20,
    firstName: "Quincy",
    lastName: "Torres",
    email: "quincy.torres@example.com",
    gender: "Male",
    phoneNumber: "555-1098",
  },
  {
    id: 21,
    firstName: "Rita",
    lastName: "Sanchez",
    email: "rita.sanchez@example.com",
    gender: "Female",
    phoneNumber: "555-9987",
  },
  {
    id: 22,
    firstName: "Steve",
    lastName: "Reed",
    email: "steve.reed@example.com",
    gender: "Male",
    phoneNumber: "555-8876",
  },
  {
    id: 23,
    firstName: "Tina",
    lastName: "Patel",
    email: "tina.patel@example.com",
    gender: "Female",
    phoneNumber: "555-7765",
  },
  {
    id: 24,
    firstName: "Uma",
    lastName: "Kim",
    email: "uma.kim@example.com",
    gender: "Female",
    phoneNumber: "555-6654",
  },
  {
    id: 25,
    firstName: "Victor",
    lastName: "Clark",
    email: "victor.clark@example.com",
    gender: "Male",
    phoneNumber: "555-5543",
  },
  {
    id: 26,
    firstName: "Wendy",
    lastName: "Baker",
    email: "wendy.baker@example.com",
    gender: "Female",
    phoneNumber: "555-4432",
  },
  {
    id: 27,
    firstName: "Xavier",
    lastName: "Adams",
    email: "xavier.adams@example.com",
    gender: "Male",
    phoneNumber: "555-3321",
  },
  {
    id: 28,
    firstName: "Yara",
    lastName: "Nelson",
    email: "yara.nelson@example.com",
    gender: "Female",
    phoneNumber: "555-2210",
  },
  {
    id: 29,
    firstName: "Zack",
    lastName: "King",
    email: "zack.king@example.com",
    gender: "Male",
    phoneNumber: "555-1109",
  },
  {
    id: 30,
    firstName: "Abby",
    lastName: "Carter",
    email: "abby.carter@example.com",
    gender: "Female",
    phoneNumber: "555-0098",
  },
  {
    id: 31,
    firstName: "Ben",
    lastName: "Evans",
    email: "ben.evans@example.com",
    gender: "Male",
    phoneNumber: "555-8987",
  },
  {
    id: 32,
    firstName: "Cathy",
    lastName: "Harris",
    email: "cathy.harris@example.com",
    gender: "Female",
    phoneNumber: "555-7876",
  },
  {
    id: 33,
    firstName: "David",
    lastName: "Walker",
    email: "david.walker@example.com",
    gender: "Male",
    phoneNumber: "555-6765",
  },
  {
    id: 34,
    firstName: "Ella",
    lastName: "Hall",
    email: "ella.hall@example.com",
    gender: "Female",
    phoneNumber: "555-5654",
  },
  {
    id: 35,
    firstName: "Frank",
    lastName: "Young",
    email: "frank.young@example.com",
    gender: "Male",
    phoneNumber: "555-4543",
  },
  {
    id: 36,
    firstName: "Gina",
    lastName: "Allen",
    email: "gina.allen@example.com",
    gender: "Female",
    phoneNumber: "555-3432",
  },
  {
    id: 37,
    firstName: "Harry",
    lastName: "Wright",
    email: "harry.wright@example.com",
    gender: "Male",
    phoneNumber: "555-2321",
  },
  {
    id: 38,
    firstName: "Ivy",
    lastName: "Scott",
    email: "ivy.scott@example.com",
    gender: "Female",
    phoneNumber: "555-1210",
  },
  {
    id: 39,
    firstName: "Jake",
    lastName: "Collins",
    email: "jake.collins@example.com",
    gender: "Male",
    phoneNumber: "555-0099",
  },
  {
    id: 40,
    firstName: "Karen",
    lastName: "Turner",
    email: "karen.turner@example.com",
    gender: "Female",
    phoneNumber: "555-9986",
  },
  {
    id: 41,
    firstName: "Luke",
    lastName: "Parker",
    email: "luke.parker@example.com",
    gender: "Male",
    phoneNumber: "555-8875",
  },
  {
    id: 42,
    firstName: "Molly",
    lastName: "Edwards",
    email: "molly.edwards@example.com",
    gender: "Female",
    phoneNumber: "555-7764",
  },
  {
    id: 43,
    firstName: "Nathan",
    lastName: "Jenkins",
    email: "nathan.jenkins@example.com",
    gender: "Male",
    phoneNumber: "555-6653",
  },
  {
    id: 44,
    firstName: "Olivia",
    lastName: "Kelly",
    email: "olivia.kelly@example.com",
    gender: "Female",
    phoneNumber: "555-5542",
  },
  {
    id: 45,
    firstName: "Peter",
    lastName: "Foster",
    email: "peter.foster@example.com",
    gender: "Male",
    phoneNumber: "555-4431",
  },
  {
    id: 46,
    firstName: "Quinn",
    lastName: "Griffin",
    email: "quinn.griffin@example.com",
    gender: "Male",
    phoneNumber: "555-3320",
  },
  {
    id: 47,
    firstName: "Rachel",
    lastName: "Murphy",
    email: "rachel.murphy@example.com",
    gender: "Female",
    phoneNumber: "555-2219",
  },
  {
    id: 48,
    firstName: "Sophie",
    lastName: "Rivera",
    email: "sophie.rivera@example.com",
    gender: "Female",
    phoneNumber: "555-1108",
  },
  {
    id: 49,
    firstName: "Tom",
    lastName: "Bailey",
    email: "tom.bailey@example.com",
    gender: "Male",
    phoneNumber: "555-0097",
  },
  {
    id: 50,
    firstName: "Uma",
    lastName: "Hughes",
    email: "uma.hughes@example.com",
    gender: "Female",
    phoneNumber: "555-8986",
  },
];
